-- Migration: 0050_seed_all_cities.sql
-- Description: Insert seluruh 500+ Kota/Kabupaten ke SEO Metadata

INSERT OR REPLACE INTO seo_city_metadata (city_name, province, local_fact) VALUES
('Aceh Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Aceh Barat'),
('Aceh Barat Daya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Aceh Barat Daya'),
('Aceh Besar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Aceh Besar'),
('Aceh Jaya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Aceh Jaya'),
('Aceh Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Aceh Selatan'),
('Aceh Singkil', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Aceh Singkil'),
('Aceh Tamiang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Aceh Tamiang'),
('Aceh Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Aceh Tengah'),
('Aceh Tenggara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Aceh Tenggara'),
('Aceh Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Aceh Timur'),
('Aceh Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Aceh Utara'),
('Agam', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Agam'),
('Alor', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Alor'),
('Ambon', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ambon'),
('Asahan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Asahan'),
('Asmat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Asmat'),
('Badung', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Badung'),
('Balangan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Balangan'),
('Balikpapan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Balikpapan'),
('Banda Aceh', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Banda Aceh'),
('Bandar Lampung', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bandar Lampung'),
('Bandung', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bandung'),
('Bandung Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bandung Barat'),
('Banggai', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Banggai'),
('Banggai Kepulauan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Banggai Kepulauan'),
('Banggai Laut', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Banggai Laut'),
('Bangka', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bangka'),
('Bangka Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bangka Barat'),
('Bangka Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bangka Selatan'),
('Bangka Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bangka Tengah'),
('Bangkalan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bangkalan'),
('Bangli', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bangli'),
('Banjar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Banjar'),
('Banjarbaru', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Banjarbaru'),
('Banjarmasin', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Banjarmasin'),
('Banjarnegara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Banjarnegara'),
('Bantaeng', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bantaeng'),
('Bantul', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bantul'),
('Banyuasin', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Banyuasin'),
('Banyumas', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Banyumas'),
('Banyuwangi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Banyuwangi'),
('Barito Kuala', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Barito Kuala'),
('Barito Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Barito Selatan'),
('Barito Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Barito Timur'),
('Barito Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Barito Utara'),
('Barru', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Barru'),
('Batam', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Batam'),
('Batang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Batang'),
('Batanghari', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Batanghari'),
('Batu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Batu'),
('Batu Bara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Batu Bara'),
('Bau-Bau', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bau-Bau'),
('Bekasi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bekasi'),
('Belitung', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Belitung'),
('Belitung Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Belitung Timur'),
('Belu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Belu'),
('Bengkalis', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bengkalis'),
('Bengkayang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bengkayang'),
('Bengkulu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bengkulu'),
('Bengkulu Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bengkulu Selatan'),
('Bengkulu Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bengkulu Tengah'),
('Bengkulu Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bengkulu Utara'),
('Berau', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Berau'),
('Biak Numfor', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Biak Numfor'),
('Bima', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bima'),
('Binjai', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Binjai'),
('Bintan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bintan'),
('Bireuen', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bireuen'),
('Bitung', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bitung'),
('Blitar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Blitar'),
('Blora', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Blora'),
('Boalemo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Boalemo'),
('Bogor', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bogor'),
('Bojonegoro', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bojonegoro'),
('Bolaang Mongondow', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bolaang Mongondow'),
('Bolaang Mongondow Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bolaang Mongondow Selatan'),
('Bolaang Mongondow Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bolaang Mongondow Timur'),
('Bolaang Mongondow Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bolaang Mongondow Utara'),
('Bombana', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bombana'),
('Bondowoso', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bondowoso'),
('Bone', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bone'),
('Bone Bolango', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bone Bolango'),
('Bontang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bontang'),
('Boven Digoel', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Boven Digoel'),
('Boyolali', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Boyolali'),
('Brebes', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Brebes'),
('Bukittinggi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bukittinggi'),
('Buleleng', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Buleleng'),
('Bulukumba', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bulukumba'),
('Bulungan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bulungan'),
('Bungo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Bungo'),
('Buol', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Buol'),
('Buru', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Buru'),
('Buru Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Buru Selatan'),
('Buton', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Buton'),
('Buton Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Buton Selatan'),
('Buton Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Buton Tengah'),
('Buton Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Buton Utara'),
('Ciamis', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ciamis'),
('Cianjur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Cianjur'),
('Cilacap', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Cilacap'),
('Cilegon', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Cilegon'),
('Cimahi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Cimahi'),
('Cirebon', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Cirebon'),
('Dairi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Dairi'),
('Deiyai', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Deiyai'),
('Deli Serdang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Deli Serdang'),
('Demak', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Demak'),
('Denpasar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Denpasar'),
('Depok', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Depok'),
('Dharmasraya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Dharmasraya'),
('Dogiyai', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Dogiyai'),
('Dompu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Dompu'),
('Donggala', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Donggala'),
('Dumai', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Dumai'),
('Empat Lawang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Empat Lawang'),
('Ende', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ende'),
('Enrekang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Enrekang'),
('Fakfak', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Fakfak'),
('Flores Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Flores Timur'),
('Garut', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Garut'),
('Gayo Lues', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Gayo Lues'),
('Gianyar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Gianyar'),
('Gorontalo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Gorontalo'),
('Gorontalo Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Gorontalo Utara'),
('Gowa', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Gowa'),
('Gresik', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Gresik'),
('Grobogan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Grobogan'),
('Gunung Mas', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Gunung Mas'),
('Gunungkidul', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Gunungkidul'),
('Gunungsitoli', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Gunungsitoli'),
('Halmahera Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Halmahera Barat'),
('Halmahera Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Halmahera Selatan'),
('Halmahera Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Halmahera Tengah'),
('Halmahera Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Halmahera Timur'),
('Halmahera Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Halmahera Utara'),
('Hulu Sungai Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Hulu Sungai Selatan'),
('Hulu Sungai Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Hulu Sungai Tengah'),
('Hulu Sungai Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Hulu Sungai Utara'),
('Humbang Hasundutan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Humbang Hasundutan'),
('Indragiri Hilir', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Indragiri Hilir'),
('Indragiri Hulu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Indragiri Hulu'),
('Indramayu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Indramayu'),
('Intan Jaya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Intan Jaya'),
('Jakarta Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jakarta Barat'),
('Jakarta Pusat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jakarta Pusat'),
('Jakarta Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jakarta Selatan'),
('Jakarta Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jakarta Timur'),
('Jakarta Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jakarta Utara'),
('Jambi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jambi'),
('Jayapura', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jayapura'),
('Jayawijaya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jayawijaya'),
('Jember', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jember'),
('Jembrana', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jembrana'),
('Jeneponto', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jeneponto'),
('Jepara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jepara'),
('Jombang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Jombang'),
('Kaimana', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kaimana'),
('Kampar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kampar'),
('Kapuas', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kapuas'),
('Kapuas Hulu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kapuas Hulu'),
('Karanganyar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Karanganyar'),
('Karangasem', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Karangasem'),
('Karawang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Karawang'),
('Karimun', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Karimun'),
('Karo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Karo'),
('Katingan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Katingan'),
('Kaur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kaur'),
('Kayong Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kayong Utara'),
('Kebumen', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kebumen'),
('Kediri', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kediri'),
('Keerom', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Keerom'),
('Kendal', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kendal'),
('Kendari', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kendari'),
('Kepulauan Anambas', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kepulauan Anambas'),
('Kepulauan Aru', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kepulauan Aru'),
('Kepulauan Mentawai', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kepulauan Mentawai'),
('Kepulauan Meranti', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kepulauan Meranti'),
('Kepulauan Sangihe', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kepulauan Sangihe'),
('Kepulauan Selayar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kepulauan Selayar'),
('Kepulauan Seribu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kepulauan Seribu'),
('Kepulauan Siau Tagulandang Biaro', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kepulauan Siau Tagulandang Biaro'),
('Kepulauan Sula', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kepulauan Sula'),
('Kepulauan Talaud', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kepulauan Talaud'),
('Kepulauan Yapen', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kepulauan Yapen'),
('Kerinci', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kerinci'),
('Ketapang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ketapang'),
('Klaten', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Klaten'),
('Klungkung', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Klungkung'),
('Kolaka', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kolaka'),
('Kolaka Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kolaka Timur'),
('Kolaka Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kolaka Utara'),
('Konawe', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Konawe'),
('Konawe Kepulauan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Konawe Kepulauan'),
('Konawe Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Konawe Selatan'),
('Konawe Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Konawe Utara'),
('Kotabaru', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kotabaru'),
('Kotamobagu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kotamobagu'),
('Kotawaringin Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kotawaringin Barat'),
('Kotawaringin Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kotawaringin Timur'),
('Kuantan Singingi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kuantan Singingi'),
('Kubu Raya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kubu Raya'),
('Kudus', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kudus'),
('Kulon Progo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kulon Progo'),
('Kuningan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kuningan'),
('Kupang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kupang'),
('Kutai Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kutai Barat'),
('Kutai Kartanegara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kutai Kartanegara'),
('Kutai Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Kutai Timur'),
('Labuhanbatu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Labuhanbatu'),
('Labuhanbatu Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Labuhanbatu Selatan'),
('Labuhanbatu Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Labuhanbatu Utara'),
('Lahat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lahat'),
('Lamandau', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lamandau'),
('Lamongan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lamongan'),
('Lampung Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lampung Barat'),
('Lampung Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lampung Selatan'),
('Lampung Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lampung Tengah'),
('Lampung Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lampung Timur'),
('Lampung Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lampung Utara'),
('Landak', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Landak'),
('Langkat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Langkat'),
('Langsa', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Langsa'),
('Lanny Jaya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lanny Jaya'),
('Lebak', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lebak'),
('Lebong', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lebong'),
('Lembata', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lembata'),
('Lhokseumawe', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lhokseumawe'),
('Lima Puluh Kota', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lima Puluh Kota'),
('Lingga', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lingga'),
('Lombok Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lombok Barat'),
('Lombok Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lombok Tengah'),
('Lombok Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lombok Timur'),
('Lombok Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lombok Utara'),
('Lubuklinggau', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lubuklinggau'),
('Lumajang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Lumajang'),
('Luwu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Luwu'),
('Luwu Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Luwu Timur'),
('Luwu Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Luwu Utara'),
('Madiun', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Madiun'),
('Magelang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Magelang'),
('Magetan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Magetan'),
('Mahakam Ulu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mahakam Ulu'),
('Majalengka', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Majalengka'),
('Majene', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Majene'),
('Makassar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Makassar'),
('Malaka', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Malaka'),
('Malang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Malang'),
('Malinau', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Malinau'),
('Maluku Barat Daya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Maluku Barat Daya'),
('Maluku Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Maluku Tengah'),
('Maluku Tenggara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Maluku Tenggara'),
('Mamasa', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mamasa'),
('Mamberamo Raya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mamberamo Raya'),
('Mamberamo Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mamberamo Tengah'),
('Mamuju', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mamuju'),
('Mamuju Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mamuju Tengah'),
('Manado', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Manado'),
('Mandailing Natal', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mandailing Natal'),
('Manggarai', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Manggarai'),
('Manggarai Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Manggarai Barat'),
('Manggarai Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Manggarai Timur'),
('Manokwari', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Manokwari'),
('Manokwari Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Manokwari Selatan'),
('Mappi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mappi'),
('Maros', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Maros'),
('Mataram', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mataram'),
('Maybrat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Maybrat'),
('Medan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Medan'),
('Melawi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Melawi'),
('Mempawah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mempawah'),
('Merangin', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Merangin'),
('Merauke', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Merauke'),
('Mesuji', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mesuji'),
('Metro', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Metro'),
('Mimika', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mimika'),
('Minahasa', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Minahasa'),
('Minahasa Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Minahasa Selatan'),
('Minahasa Tenggara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Minahasa Tenggara'),
('Minahasa Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Minahasa Utara'),
('Mojokerto', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mojokerto'),
('Morowali', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Morowali'),
('Morowali Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Morowali Utara'),
('Muara Enim', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Muara Enim'),
('Muaro Jambi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Muaro Jambi'),
('Mukomuko', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Mukomuko'),
('Muna', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Muna'),
('Muna Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Muna Barat'),
('Murung Raya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Murung Raya'),
('Musi Banyuasin', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Musi Banyuasin'),
('Musi Rawas', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Musi Rawas'),
('Musi Rawas Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Musi Rawas Utara'),
('Nabire', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Nabire'),
('Nagan Raya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Nagan Raya'),
('Nagekeo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Nagekeo'),
('Natuna', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Natuna'),
('Nduga', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Nduga'),
('Ngada', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ngada'),
('Nganjuk', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Nganjuk'),
('Ngawi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ngawi'),
('Nias', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Nias'),
('Nias Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Nias Barat'),
('Nias Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Nias Selatan'),
('Nias Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Nias Utara'),
('Nunukan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Nunukan'),
('Ogan Ilir', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ogan Ilir'),
('Ogan Komering Ilir', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ogan Komering Ilir'),
('Ogan Komering Ulu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ogan Komering Ulu'),
('Ogan Komering Ulu Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ogan Komering Ulu Selatan'),
('Ogan Komering Ulu Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ogan Komering Ulu Timur'),
('Pacitan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pacitan'),
('Padang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Padang'),
('Padang Lawas', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Padang Lawas'),
('Padang Lawas Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Padang Lawas Utara'),
('Padang Panjang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Padang Panjang'),
('Padang Pariaman', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Padang Pariaman'),
('Padangsidimpuan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Padangsidimpuan'),
('Pagar Alam', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pagar Alam'),
('Pakpak Bharat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pakpak Bharat'),
('Palangka Raya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Palangka Raya'),
('Palembang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Palembang'),
('Palopo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Palopo'),
('Palu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Palu'),
('Pamekasan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pamekasan'),
('Pandeglang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pandeglang'),
('Pangandaran', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pangandaran'),
('Pangkajene dan Kepulauan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pangkajene dan Kepulauan'),
('Pangkal Pinang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pangkal Pinang'),
('Paniai', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Paniai'),
('Parepare', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Parepare'),
('Pariaman', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pariaman'),
('Parigi Moutong', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Parigi Moutong'),
('Pasaman', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pasaman'),
('Pasaman Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pasaman Barat'),
('Paser', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Paser'),
('Pasuruan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pasuruan'),
('Pati', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pati'),
('Payakumbuh', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Payakumbuh'),
('Pegunungan Arfak', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pegunungan Arfak'),
('Pegunungan Bintang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pegunungan Bintang'),
('Pekalongan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pekalongan'),
('Pekanbaru', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pekanbaru'),
('Pelalawan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pelalawan'),
('Pemalang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pemalang'),
('Pematangsiantar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pematangsiantar'),
('Penajam Paser Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Penajam Paser Utara'),
('Penukal Abab Lematang Ilir', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Penukal Abab Lematang Ilir'),
('Pesawaran', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pesawaran'),
('Pesisir Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pesisir Barat'),
('Pesisir Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pesisir Selatan'),
('Pidie', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pidie'),
('Pidie Jaya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pidie Jaya'),
('Pinrang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pinrang'),
('Pohuwato', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pohuwato'),
('Polewali Mandar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Polewali Mandar'),
('Ponorogo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ponorogo'),
('Pontianak', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pontianak'),
('Poso', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Poso'),
('Prabumulih', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Prabumulih'),
('Pringsewu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pringsewu'),
('Probolinggo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Probolinggo'),
('Pulang Pisau', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pulang Pisau'),
('Pulau Morotai', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pulau Morotai'),
('Pulau Taliabu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Pulau Taliabu'),
('Puncak', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Puncak'),
('Puncak Jaya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Puncak Jaya'),
('Purwakarta', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Purwakarta'),
('Purworejo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Purworejo'),
('Raja Ampat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Raja Ampat'),
('Rejang Lebong', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Rejang Lebong'),
('Rembang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Rembang'),
('Rokan Hilir', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Rokan Hilir'),
('Rokan Hulu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Rokan Hulu'),
('Rote Ndao', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Rote Ndao'),
('Sabang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sabang'),
('Sabu Raijua', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sabu Raijua'),
('Salatiga', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Salatiga'),
('Samarinda', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Samarinda'),
('Sambas', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sambas'),
('Samosir', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Samosir'),
('Sampang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sampang'),
('Sanggau', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sanggau'),
('Sarmi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sarmi'),
('Sarolangun', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sarolangun'),
('Sawahlunto', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sawahlunto'),
('Sekadau', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sekadau'),
('Seluma', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Seluma'),
('Semarang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Semarang'),
('Seram Bagian Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Seram Bagian Barat'),
('Seram Bagian Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Seram Bagian Timur'),
('Serang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Serang'),
('Serdang Bedagai', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Serdang Bedagai'),
('Seruyan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Seruyan'),
('Siak', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Siak'),
('Sibolga', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sibolga'),
('Sidenreng Rappang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sidenreng Rappang'),
('Sidoarjo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sidoarjo'),
('Sigi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sigi'),
('Sijunjung', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sijunjung'),
('Sikka', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sikka'),
('Simalungun', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Simalungun'),
('Simeulue', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Simeulue'),
('Singkawang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Singkawang'),
('Sinjai', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sinjai'),
('Sintang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sintang'),
('Situbondo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Situbondo'),
('Sleman', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sleman'),
('Solok', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Solok'),
('Solok Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Solok Selatan'),
('Soppeng', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Soppeng'),
('Sorong', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sorong'),
('Sorong Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sorong Selatan'),
('Sragen', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sragen'),
('Subang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Subang'),
('Subulussalam', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Subulussalam'),
('Sukabumi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sukabumi'),
('Sukamara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sukamara'),
('Sukoharjo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sukoharjo'),
('Sumba Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sumba Barat'),
('Sumba Barat Daya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sumba Barat Daya'),
('Sumba Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sumba Tengah'),
('Sumba Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sumba Timur'),
('Sumbawa', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sumbawa'),
('Sumbawa Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sumbawa Barat'),
('Sumedang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sumedang'),
('Sumenep', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sumenep'),
('Sungai Penuh', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Sungai Penuh'),
('Supiori', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Supiori'),
('Surabaya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Surabaya'),
('Surakarta', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Surakarta'),
('Tabalong', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tabalong'),
('Tabanan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tabanan'),
('Takalar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Takalar'),
('Tana Tidung', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tana Tidung'),
('Tana Toraja', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tana Toraja'),
('Tanah Bumbu', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tanah Bumbu'),
('Tanah Datar', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tanah Datar'),
('Tanah Laut', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tanah Laut'),
('Tangerang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tangerang'),
('Tangerang Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tangerang Selatan'),
('Tanggamus', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tanggamus'),
('Tanjung Balai', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tanjung Balai'),
('Tanjung Jabung Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tanjung Jabung Barat'),
('Tanjung Jabung Timur', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tanjung Jabung Timur'),
('Tanjung Pinang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tanjung Pinang'),
('Tapanuli Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tapanuli Selatan'),
('Tapanuli Tengah', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tapanuli Tengah'),
('Tapanuli Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tapanuli Utara'),
('Tapin', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tapin'),
('Tarakan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tarakan'),
('Tasikmalaya', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tasikmalaya'),
('Tebing Tinggi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tebing Tinggi'),
('Tebo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tebo'),
('Tegal', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tegal'),
('Teluk Bintuni', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Teluk Bintuni'),
('Teluk Wondama', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Teluk Wondama'),
('Temanggung', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Temanggung'),
('Ternate', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Ternate'),
('Tidore Kepulauan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tidore Kepulauan'),
('Timor Tengah Selatan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Timor Tengah Selatan'),
('Timor Tengah Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Timor Tengah Utara'),
('Toba Samosir', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Toba Samosir'),
('Tojo Una-Una', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tojo Una-Una'),
('Tolikara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tolikara'),
('Tolitoli', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tolitoli'),
('Tomohon', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tomohon'),
('Toraja Utara', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Toraja Utara'),
('Trenggalek', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Trenggalek'),
('Tual', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tual'),
('Tuban', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tuban'),
('Tulang Bawang', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tulang Bawang'),
('Tulang Bawang Barat', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tulang Bawang Barat'),
('Tulungagung', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Tulungagung'),
('Wajo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Wajo'),
('Wakatobi', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Wakatobi'),
('Waropen', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Waropen'),
('Way Kanan', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Way Kanan'),
('Wonogiri', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Wonogiri'),
('Wonosobo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Wonosobo'),
('Yahukimo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Yahukimo'),
('Yalimo', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Yalimo'),
('Yogyakarta', 'Indonesia', 'Pusat vendor pernikahan dan acara terbaik di wilayah Yogyakarta');
