name = "tamuu-worker"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

routes = [
    { pattern = "tamuu.id/*", zone_id = "892dbe6c5414762f7d6b25f5f2a87c97" },
    { pattern = "www.tamuu.id/*", zone_id = "892dbe6c5414762f7d6b25f5f2a87c97" }
]

[site]
bucket = ".open-next/assets"

[vars]
NEXTJS_ENV = "production"
