export interface FontConfig {
    name: string;
    family: string;
    category: 'sans-serif' | 'serif' | 'display' | 'handwriting' | 'monospace';
}

export const SUPPORTED_FONTS: FontConfig[] = [
    // --- SANS-SERIF & SERIF (80 fonts - 40%) ---
    { name: 'Plus Jakarta Sans', family: "'Plus Jakarta Sans', sans-serif", category: 'sans-serif' },
    { name: 'Inter', family: "'Inter', sans-serif", category: 'sans-serif' },
    { name: 'Outfit', family: "'Outfit', sans-serif", category: 'sans-serif' },
    { name: 'Montserrat', family: "'Montserrat', sans-serif", category: 'sans-serif' },
    { name: 'Poppins', family: "'Poppins', sans-serif", category: 'sans-serif' },
    { name: 'Roboto', family: "'Roboto', sans-serif", category: 'sans-serif' },
    { name: 'Open Sans', family: "'Open Sans', sans-serif", category: 'sans-serif' },
    { name: 'Lato', family: "'Lato', sans-serif", category: 'sans-serif' },
    { name: 'Nunito', family: "'Nunito', sans-serif", category: 'sans-serif' },
    { name: 'Quicksand', family: "'Quicksand', sans-serif", category: 'sans-serif' },
    { name: 'Josefin Sans', family: "'Josefin Sans', sans-serif", category: 'sans-serif' },
    { name: 'Manrope', family: "'Manrope', sans-serif", category: 'sans-serif' },
    { name: 'Urbanist', family: "'Urbanist', sans-serif", category: 'sans-serif' },
    { name: 'DM Sans', family: "'DM Sans', sans-serif", category: 'sans-serif' },
    { name: 'Space Grotesk', family: "'Space Grotesk', sans-serif", category: 'sans-serif' },
    { name: 'Syne', family: "'Syne', sans-serif", category: 'sans-serif' },
    { name: 'Lexend', family: "'Lexend', sans-serif", category: 'sans-serif' },
    { name: 'Work Sans', family: "'Work Sans', sans-serif", category: 'sans-serif' },
    { name: 'Archivo', family: "'Archivo', sans-serif", category: 'sans-serif' },
    { name: 'Sora', family: "'Sora', sans-serif", category: 'sans-serif' },
    { name: 'Kanit', family: "'Kanit', sans-serif", category: 'sans-serif' },
    { name: 'Heebo', family: "'Heebo', sans-serif", category: 'sans-serif' },
    { name: 'Cabin', family: "'Cabin', sans-serif", category: 'sans-serif' },
    { name: 'Barlow', family: "'Barlow', sans-serif", category: 'sans-serif' },
    { name: 'Overpass', family: "'Overpass', sans-serif", category: 'sans-serif' },
    { name: 'Titillium Web', family: "'Titillium Web', sans-serif", category: 'sans-serif' },
    { name: 'Assistant', family: "'Assistant', sans-serif", category: 'sans-serif' },
    { name: 'Jost', family: "'Jost', sans-serif", category: 'sans-serif' },
    { name: 'Ubuntu', family: "'Ubuntu', sans-serif", category: 'sans-serif' },
    { name: 'Mukta', family: "'Mukta', sans-serif", category: 'sans-serif' },
    { name: 'Hind', family: "'Hind', sans-serif", category: 'sans-serif' },
    { name: 'Noto Sans', family: "'Noto Sans', sans-serif", category: 'sans-serif' },
    { name: 'Arimo', family: "'Arimo', sans-serif", category: 'sans-serif' },
    { name: 'Playfair Display', family: "'Playfair Display', serif", category: 'serif' },
    { name: 'Lora', family: "'Lora', serif", category: 'serif' },
    { name: 'Merriweather', family: "'Merriweather', serif", category: 'serif' },
    { name: 'PT Serif', family: "'PT Serif', serif", category: 'serif' },
    { name: 'Crimson Text', family: "'Crimson Text', serif", category: 'serif' },
    { name: 'Libre Baskerville', family: "'Libre Baskerville', serif", category: 'serif' },
    { name: 'Cormorant Garamond', family: "'Cormorant Garamond', serif", category: 'serif' },
    { name: 'EB Garamond', family: "'EB Garamond', serif", category: 'serif' },
    { name: 'Cinzel', family: "'Cinzel', serif", category: 'serif' },
    { name: 'Bodoni Moda', family: "'Bodoni Moda', serif", category: 'serif' },
    { name: 'Marcellus', family: "'Marcellus', serif", category: 'serif' },
    { name: 'Prata', family: "'Prata', serif", category: 'serif' },
    { name: 'Spectral', family: "'Spectral', serif", category: 'serif' },
    { name: 'Old Standard TT', family: "'Old Standard TT', serif", category: 'serif' },
    { name: 'Cardo', family: "'Cardo', serif", category: 'serif' },
    { name: 'Gilda Display', family: "'Gilda Display', serif", category: 'serif' },
    { name: 'Alice', family: "'Alice', serif", category: 'serif' },
    { name: 'Abhaya Libre', family: "'Abhaya Libre', serif", category: 'serif' },
    { name: 'Fraunces', family: "'Fraunces', serif", category: 'serif' },
    { name: 'Domine', family: "'Domine', serif", category: 'serif' },
    { name: 'Bitter', family: "'Bitter', serif", category: 'serif' },
    { name: 'Arvo', family: "'Arvo', serif", category: 'serif' },
    { name: 'Bree Serif', family: "'Bree Serif', serif", category: 'serif' },
    { name: 'Patua One', family: "'Patua One', serif", category: 'serif' },
    { name: 'Zilla Slab', family: "'Zilla Slab', serif", category: 'serif' },
    { name: 'BioRhyme', family: "'BioRhyme', serif", category: 'serif' },
    { name: 'Abel', family: "'Abel', sans-serif", category: 'sans-serif' },
    { name: 'Anton', family: "'Anton', sans-serif", category: 'sans-serif' },
    { name: 'Bebas Neue', family: "'Bebas Neue', sans-serif", category: 'sans-serif' },
    { name: 'Exo 2', family: "'Exo 2', sans-serif", category: 'sans-serif' },
    { name: 'Fira Sans', family: "'Fira Sans', sans-serif", category: 'sans-serif' },
    { name: 'Inconsolata', family: "'Inconsolata', monospace", category: 'monospace' },
    { name: 'Josefin Slab', family: "'Josefin Slab', serif", category: 'serif' },
    { name: 'Muli', family: "'Muli', sans-serif", category: 'sans-serif' },
    { name: 'Oxygen', family: "'Oxygen', sans-serif", category: 'sans-serif' },
    { name: 'Questrial', family: "'Questrial', sans-serif", category: 'sans-serif' },
    { name: 'Rokkitt', family: "'Rokkitt', serif", category: 'serif' },
    { name: 'Source Sans Pro', family: "'Source Sans Pro', sans-serif", category: 'sans-serif' },
    { name: 'Source Serif Pro', family: "'Source Serif Pro', serif", category: 'serif' },
    { name: 'Teko', family: "'Teko', sans-serif", category: 'sans-serif' },
    { name: 'Vollkorn', family: "'Vollkorn', serif", category: 'serif' },
    { name: 'Yantramanav', family: "'Yantramanav', sans-serif", category: 'sans-serif' },
    { name: 'Zcool Xiaowei', family: "'Zcool Xiaowei', serif", category: 'serif' },
    { name: 'Amiri', family: "'Amiri', serif", category: 'serif' },
    { name: 'Asap', family: "'Asap', sans-serif", category: 'sans-serif' },
    { name: 'Catamaran', family: "'Catamaran', sans-serif", category: 'sans-serif' },
    { name: 'Dosis', family: "'Dosis', sans-serif", category: 'sans-serif' },

    // --- HANDWRITING / CURSIVE / TEGAK BERSAMBUNG (120 fonts - 60%) ---
    { name: 'Dancing Script', family: "'Dancing Script', cursive", category: 'handwriting' },
    { name: 'Great Vibes', family: "'Great Vibes', cursive", category: 'handwriting' },
    { name: 'Pacifico', family: "'Pacifico', cursive", category: 'handwriting' },
    { name: 'Satisfy', family: "'Satisfy', cursive", category: 'handwriting' },
    { name: 'Alex Brush', family: "'Alex Brush', cursive", category: 'handwriting' },
    { name: 'Allura', family: "'Allura', cursive", category: 'handwriting' },
    { name: 'Arizonia', family: "'Arizonia', cursive", category: 'handwriting' },
    { name: 'Bad Script', family: "'Bad Script', cursive", category: 'handwriting' },
    { name: 'Cookie', family: "'Cookie', cursive", category: 'handwriting' },
    { name: 'Courgette', family: "'Courgette', cursive", category: 'handwriting' },
    { name: 'Damion', family: "'Damion', cursive", category: 'handwriting' },
    { name: 'Kaushan Script', family: "'Kaushan Script', cursive", category: 'handwriting' },
    { name: 'Lobster', family: "'Lobster', cursive", category: 'handwriting' },
    { name: 'Lobster Two', family: "'Lobster Two', cursive", category: 'handwriting' },
    { name: 'Marck Script', family: "'Marck Script', cursive", category: 'handwriting' },
    { name: 'Monsieur La Doulaise', family: "'Monsieur La Doulaise', cursive", category: 'handwriting' },
    { name: 'Mr De Haviland', family: "'Mr De Haviland', cursive", category: 'handwriting' },
    { name: 'Mrs Saint Delafield', family: "'Mrs Saint Delafield', cursive", category: 'handwriting' },
    { name: 'Oleo Script', family: "'Oleo Script', cursive", category: 'handwriting' },
    { name: 'Parisienne', family: "'Parisienne', cursive", category: 'handwriting' },
    { name: 'Pinyon Script', family: "'Pinyon Script', cursive", category: 'handwriting' },
    { name: 'Rochester', family: "'Rochester', cursive", category: 'handwriting' },
    { name: 'Rouge Script', family: "'Rouge Script', cursive", category: 'handwriting' },
    { name: 'Sacramento', family: "'Sacramento', cursive", category: 'handwriting' },
    { name: 'Seaweed Script', family: "'Seaweed Script', cursive", category: 'handwriting' },
    { name: 'Tangerine', family: "'Tangerine', cursive", category: 'handwriting' },
    { name: 'Yellowtail', family: "'Yellowtail', cursive", category: 'handwriting' },
    { name: 'Windsong', family: "'Windsong', cursive", category: 'handwriting' },
    { name: 'Niconne', family: "'Niconne', cursive", category: 'handwriting' },
    { name: 'Clicker Script', family: "'Clicker Script', cursive", category: 'handwriting' },
    { name: 'Meie Script', family: "'Meie Script', cursive", category: 'handwriting' },
    { name: 'Petit Formal Script', family: "'Petit Formal Script', cursive", category: 'handwriting' },
    { name: 'Ruthie', family: "'Ruthie', cursive", category: 'handwriting' },
    { name: 'Stalemate', family: "'Stalemate', cursive", category: 'handwriting' },
    { name: 'Herr Von Muellerhoff', family: "'Herr Von Muellerhoff', cursive", category: 'handwriting' },
    { name: 'Italianno', family: "'Italianno', cursive", category: 'handwriting' },
    { name: 'Jim Nightshade', family: "'Jim Nightshade', cursive", category: 'handwriting' },
    { name: 'Montez', family: "'Montez', cursive", category: 'handwriting' },
    { name: 'Norican', family: "'Norican', cursive", category: 'handwriting' },
    { name: 'Quintessential', family: "'Quintessential', cursive", category: 'handwriting' },
    { name: 'Reenie Beanie', family: "'Reenie Beanie', cursive", category: 'handwriting' },
    { name: 'Rock Salt', family: "'Rock Salt', cursive", category: 'handwriting' },
    { name: 'Shadows Into Light', family: "'Shadows Into Light', cursive", category: 'handwriting' },
    { name: 'Sunshiney', family: "'Sunshiney', cursive", category: 'handwriting' },
    { name: 'Zeyada', family: "'Zeyada', cursive", category: 'handwriting' },
    { name: 'Caveat', family: "'Caveat', cursive", category: 'handwriting' },
    { name: 'Indie Flower', family: "'Indie Flower', cursive", category: 'handwriting' },
    { name: 'Shadows Into Light Two', family: "'Shadows Into Light Two', cursive", category: 'handwriting' },
    { name: 'Amatic SC', family: "'Amatic SC', cursive", category: 'handwriting' },
    { name: 'Gloria Hallelujah', family: "'Gloria Hallelujah', cursive", category: 'handwriting' },
    { name: 'Coming Soon', family: "'Coming Soon', cursive", category: 'handwriting' },
    { name: 'Handlee', family: "'Handlee', cursive", category: 'handwriting' },
    { name: 'Patrick Hand', family: "'Patrick Hand', cursive", category: 'handwriting' },
    { name: 'Architects Daughter', family: "'Architects Daughter', cursive", category: 'handwriting' },
    { name: 'Covered By Your Grace', family: "'Covered By Your Grace', cursive", category: 'handwriting' },
    { name: 'Nothing You Could Do', family: "'Nothing You Could Do', cursive", category: 'handwriting' },
    { name: 'Permanent Marker', family: "'Permanent Marker', cursive", category: 'handwriting' },
    { name: 'Homemade Apple', family: "'Homemade Apple', cursive", category: 'handwriting' },
    { name: 'Walter Turncoat', family: "'Walter Turncoat', cursive", category: 'handwriting' },
    { name: 'Short Stack', family: "'Short Stack', cursive", category: 'handwriting' },
    { name: 'Kalam', family: "'Kalam', cursive", category: 'handwriting' },
    { name: 'Gochi Hand', family: "'Gochi Hand', cursive", category: 'handwriting' },
    { name: 'Annie Use Your Telescope', family: "'Annie Use Your Telescope', cursive", category: 'handwriting' },
    { name: 'Special Elite', family: "'Special Elite', cursive", category: 'handwriting' },
    { name: 'Loved by the King', family: "'Loved by the King', cursive", category: 'handwriting' },
    { name: 'Sue Ellen Francisco', family: "'Sue Ellen Francisco', cursive", category: 'handwriting' },
    { name: 'Waiting for the Sunrise', family: "'Waiting for the Sunrise', cursive", category: 'handwriting' },
    { name: 'Crafty Girls', family: "'Crafty Girls', cursive", category: 'handwriting' },
    { name: 'Over the Rainbow', family: "'Over the Rainbow', cursive", category: 'handwriting' },
    { name: 'Just Another Hand', family: "'Just Another Hand', cursive", category: 'handwriting' },
    { name: 'Schoolbell', family: "'Schoolbell', cursive", category: 'handwriting' },
    { name: 'The Girl Next Door', family: "'The Girl Next Door', cursive", category: 'handwriting' },
    { name: 'Rancho', family: "'Rancho', cursive", category: 'handwriting' },
    { name: 'Pangolin', family: "'Pangolin', cursive", category: 'handwriting' },
    { name: 'Cedarville Cursive', family: "'Cedarville Cursive', cursive", category: 'handwriting' },
    { name: 'League Script', family: "'League Script', cursive", category: 'handwriting' },
    { name: 'Butterfly Kids', family: "'Butterfly Kids', cursive", category: 'handwriting' },
    { name: 'Engagement', family: "'Engagement', cursive", category: 'handwriting' },
    { name: 'Givyou Script', family: "'Givyou Script', cursive", category: 'handwriting' },
    { name: 'Ibarra Real Nova', family: "'Ibarra Real Nova', serif", category: 'serif' },
    { name: 'Kristi', family: "'Kristi', cursive", category: 'handwriting' },
    { name: 'La Belle Aurore', family: "'La Belle Aurore', cursive", category: 'handwriting' },
    { name: 'Meddon', family: "'Meddon', cursive", category: 'handwriting' },
    { name: 'Miss Fachard', family: "'Miss Fachard', cursive", category: 'handwriting' },
    { name: 'Molle', family: "'Molle', cursive", category: 'handwriting' },
    { name: 'MonteCarlo', family: "'MonteCarlo', cursive", category: 'handwriting' },
    { name: 'Mr Bedfort', family: "'Mr Bedfort', cursive", category: 'handwriting' },
    { name: 'Mr Dafoe', family: "'Mr Dafoe', cursive", category: 'handwriting' },
    { name: 'Mrs Sheppards', family: "'Mrs Sheppards', cursive", category: 'handwriting' },
    { name: 'Neucha', family: "'Neucha', cursive", category: 'handwriting' },
    { name: 'Oooh Baby', family: "'Oooh Baby', cursive", category: 'handwriting' },
    { name: 'Princess Sofia', family: "'Princess Sofia', cursive", category: 'handwriting' },
    { name: 'Qwigley', family: "'Qwigley', cursive", category: 'handwriting' },
    { name: 'Redressed', family: "'Redressed', cursive", category: 'handwriting' },
    { name: 'Salsa', family: "'Salsa', cursive", category: 'handwriting' },
    { name: 'Sofia', family: "'Sofia', cursive", category: 'handwriting' },
    { name: 'Square Peg', family: "'Square Peg', cursive", category: 'handwriting' },
    { name: 'Trade Winds', family: "'Trade Winds', display", category: 'display' },
    { name: 'Vibur', family: "'Vibur', cursive", category: 'handwriting' },
    { name: 'Yesteryear', family: "'Yesteryear', cursive", category: 'handwriting' },
    { name: 'Allison', family: "'Allison', cursive", category: 'handwriting' },
    { name: 'Bilbo', family: "'Bilbo', cursive", category: 'handwriting' },
    { name: 'Calligraffitti', family: "'Calligraffitti', cursive", category: 'handwriting' },
    { name: 'Dawning of a New Day', family: "'Dawning of a New Day', cursive", category: 'handwriting' },
    { name: 'Euphoria Script', family: "'Euphoria Script', cursive", category: 'handwriting' },
    { name: 'Fondamento', family: "'Fondamento', cursive", category: 'handwriting' },
    { name: 'Give You Glory', family: "'Give You Glory', cursive", category: 'handwriting' },
    { name: 'Imperial Script', family: "'Imperial Script', cursive", category: 'handwriting' },
    { name: 'Updock', family: "'Updock', cursive", category: 'handwriting' },
    { name: 'Water Brush', family: "'Water Brush', cursive", category: 'handwriting' },
    { name: 'Grape Nuts', family: "'Grape Nuts', cursive", category: 'handwriting' },
    { name: 'Island Moments', family: "'Island Moments', cursive", category: 'handwriting' },
    { name: 'Kolker Brush', family: "'Kolker Brush', cursive", category: 'handwriting' },
    { name: 'My Soul', family: "'My Soul', cursive", category: 'handwriting' },
    { name: 'Whisper', family: "'Whisper', cursive", category: 'handwriting' },
    { name: 'Grey Qo', family: "'Grey Qo', cursive", category: 'handwriting' },
    { name: 'Lavishly Yours', family: "'Lavishly Yours', cursive", category: 'handwriting' },
    { name: 'Playwrite DE Grund', family: "'Playwrite DE Grund', handwriting", category: 'handwriting' },
    { name: 'Ephesis', family: "'Ephesis', cursive", category: 'handwriting' },
    { name: 'Festive', family: "'Festive', cursive", category: 'handwriting' },
    { name: 'Fleur De Leah', family: "'Fleur De Leah', cursive", category: 'handwriting' },
    { name: 'Gluten', family: "'Gluten', cursive", category: 'handwriting' },
    { name: 'Meow Script', family: "'Meow Script', cursive", category: 'handwriting' },
    { name: 'Mochiy Pop P One', family: "'Mochiy Pop P One', sans-serif", category: 'sans-serif' },
    { name: 'MonteCarlo', family: "'MonteCarlo', cursive", category: 'handwriting' },
    { name: 'Passions Conflict', family: "'Passions Conflict', cursive", category: 'handwriting' },
    { name: 'Puppy Eyes', family: "'Puppy Eyes', cursive", category: 'handwriting' },
    { name: 'Road Rage', family: "'Road Rage', cursive", category: 'handwriting' },
    { name: 'Style Script', family: "'Style Script', cursive", category: 'handwriting' },
    { name: 'The Nautigal', family: "'The Nautigal', cursive", category: 'handwriting' },
    { name: 'Twinkle Star', family: "'Twinkle Star', cursive", category: 'handwriting' },
    { name: 'WindSong', family: "'WindSong', cursive", category: 'handwriting' },
];

export const GOOGLE_FONTS_URL = `https://fonts.googleapis.com/css2?${SUPPORTED_FONTS.map(f => `family=${f.name.replace(/ /g, '+')}`).join('&')}&display=swap`;
